language: cpp
env:
  global:
    - MINCONDA_VERSION="latest"
    - MINCONDA_LINUX="Linux-x86_64"
    - MINCONDA_OSX="MacOSX-x86_64"
matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
    - os: osx
      osx_image: xcode10
      compiler: clang
install:
    # Define the version of miniconda to download
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        MINCONDA_OS=$MINCONDA_LINUX;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        MINCONDA_OS=$MINCONDA_OSX;
      fi
    - wget "http://repo.continuum.io/miniconda/Miniconda3-$MINCONDA_VERSION-$MINCONDA_OS.sh" -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Host dependencies
    - conda install xeus=0.23.10 xtl nlohmann_json cppzmq sqlite sqlitecpp cpp-tabulate==1.0.0 -c conda-forge
    # Build dependencies
    - conda install cmake -c conda-forge
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        conda install gxx_linux-64 libgcc -c conda-forge;
      fi
    # Activate root environment
    - source activate root
# Test dependencies
    - conda install pytest jupyter_kernel_test -c conda-forge;
    # Build and install xeus-sqlite
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=$HOME/miniconda -DXSQL_DOWNLOAD_GTEST=ON  -DCMAKE_PREFIX_PATH=$HOME/miniconda ..
    - make -j2 install
script:
    - ./test/test_xeus_sqlite
