name: xeus-sqlite-wasm-host
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.mamba.pm/conda-forge
dependencies:
  - nlohmann_json
  - sqlite
  - sqlitecpp
  - cpp-tabulate=1.5
  - xvega>=0.1.3
  - xproperty>=0.12.1
  - xvega-bindings>=0.1.1
  - xeus-lite >= 4.0.0
  - xeus >= 2.4.0
