name: xeus-sqlite-wasm-host
channels:
  - https://prefix.dev/emscripten-forge-dev
  - https://prefix.dev/conda-forge
dependencies:
  - nlohmann_json >= 3.12
  - nlohmann_json-abi
  - xproperty < 0.13
  - cpp-tabulate
  - xvega
  - xvega-bindings
  - xeus-lite >=5.0,<6.0
  - xeus >=6.0,<7.0
  - sqlitecpp
